best_model: QPSO_DeepNeuralNetwork
paths:
  best_model_pkl: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth & Demographic
    Forecasting System\qpso_best_model.pkl
  dataset_path: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth & Demographic
    Forecasting System\Percentage_of_Scheduled_Caste_Population_to_Total_Population.csv
  feature_selection_json: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth
    & Demographic Forecasting System\qpso_feature_selection.json
  h5_model: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth & Demographic
    Forecasting System\qpso_deep_learning_model.h5
  json_results: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth & Demographic
    Forecasting System\qpso_results.json
  output_directory: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth &
    Demographic Forecasting System
  predictions_csv: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth &
    Demographic Forecasting System\qpso_predictions.csv
  results_csv: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth & Demographic
    Forecasting System\qpso_results.csv
  scaler_pkl: C:\Users\NXTWAVE\Downloads\Scheduled Caste Population Growth & Demographic
    Forecasting System\qpso_scaler.pkl
project:
  algorithm: QPSO
  author: Sagnik Patra
  name: Scheduled Caste Population Growth & Demographic Forecasting System
  prefix: qpso_
qpso_parameters:
  beta: 0.75
  iterations: 30
  num_particles: 25
training:
  all_features:
  - Percentage of Scheduled Caste Population _2001_Rural
  - Percentage of Scheduled Caste Population _2001_Urban
  - Percentage of Scheduled Caste Population _2001_Total
  - Percentage of Scheduled Caste Population _2011_Rural
  - Percentage of Scheduled Caste Population _2011_Urban
  - Percentage of Scheduled Caste Population _2011_Total
  - Rural_Growth
  - Urban_Growth
  - Total_Growth
  - Rural_Urban_Gap_2011
  random_state: 42
  selected_features:
  - Percentage of Scheduled Caste Population _2011_Total
  - Total_Growth
  target_column: Estimated_2021_Total_SC_Percentage
  test_size: 0.2
